### ISSUE TITLE
LND Properties tab not appearing

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/lnd-startos#29] opened 2021-10-19 18:40 UTC
This is normally a result of LND having not started up yet, but one user has it as a recurring issue.  Re-installs do not help.  Logs report "Error: missing field 'cipher_seed_mnemonic' at line 1 column 135" and "waiting for wallet encryption password," and asks for lncli commands to create or unlock a wallet.

**Comment by ProofOfKeags** [comment] 2021-10-19 19:04
I can also spin up a 0.2.x box no problem to try and reproduce this.

**Comment by kn0wmad** [comment] 2021-10-19 19:10
Sounds good, thanks for looking into this

**Comment by elvece** [comment] 2021-12-06 19:22
@kn0wmad Does this issue reflect a problem in the EOS v0.2.x version of LND?

**Comment by kn0wmad** [comment] 2021-12-06 20:54
> @kn0wmad Does this issue reflect a problem in the EOS v0.2.x version of LND?

Yes.  I filed a report for a similar issue on 0.3 however, which was my own, not of a user

**Comment by ProofOfKeags** [comment] 2021-12-06 22:47
If we can't reproduce we should probably close this as a ghost.

**Closed as completed** 2022-01-26 15:40 UTC
Labels: Bug, Ghost
